README.md

Add Vadym Musiienko to README

---

.gitignore
frontend/package-lock.json
frontend/package.json
frontend/src/app/dashboard/page.tsx
frontend/src/app/login/page.tsx
frontend/src/app/page.tsx
frontend/src/components/Loading.tsx
frontend/src/components/ui/Header.tsx
frontend/src/hooks/useAuth.ts
frontend/src/middleware.ts
frontend/tsconfig.json

- Basic Frontend Dashboard
- Middleware in Frontend: creates check for routes needing login and does addition check for admin on /dashboard
- Basic Login frontend feature and page to sync with backend routes
- useAuth custom hook to get user is logged in (option to also check for admin) status throughout app
-Loading custom component
- update Header with login/logout buttons as well as seeing dashboard link if admin

made custom dashboard that requires admin login

---

backend/src/models/PageContent.ts
backend/src/routes/AdminRoutes.ts
backend/src/server.ts

Admin pages

---

frontend/package-lock.json
frontend/package.json
frontend/src/app/dashboard/page.tsx

Fixed dependencies for tinymce and react
Upgraded nextjs for suggested security reasons

Dependencies

---

backend/src/server.ts
frontend/next.config.ts
frontend/src/app/aspc/[slug]/page.tsx
frontend/src/app/login/page.tsx
frontend/src/app/staff/[slug]/page.tsx
frontend/src/components/ui/Header.tsx
frontend/src/components/ui/PageDashboard.tsx
frontend/src/components/ui/StaffDashboard.tsx
frontend/src/hooks/useAuth.ts
frontend/src/middleware.ts

Changed "http://localhost:5000" to "${process.env.BackendLink}"

Add process.env.BackendLink

---

backend/src/routes/AdminRoutes.ts
frontend/src/components/ui/PageDashboard.tsx

Add delete functionality for Admin pages (backend only)

---

frontend/src/components/ui/Header.tsx

Updated the mobile navbar to prevent title overlap
(Made it look like the one ASCMC has)

fix: mobile header (dropdown overlay)

---

backend/src/routes/AdminRoutes.ts
frontend/src/components/ui/PageDashboard.tsx

Allow admins to edit page name and id

Edit page name and id in admin dashboard

---

frontend/src/app/dashboard/page.tsx
frontend/src/app/page.tsx
frontend/src/app/staff/[slug]/page.tsx
frontend/src/components/ui/Header.tsx

Fixed the padding on the header for the admin dashboard and prevented the filter for the photo from rendering before the photo.

Fixed admin header padding and home screen loading

---

frontend/src/components/ui/Header.tsx

Refactored Header: Combined Campus, Courses, and Chirp Guide into Resources dropdown

Refactored Header

---

frontend/src/components/ui/Header.tsx

Small fixes to header
- Add Elections tab
- Rename Members to Officers
- Make logo in mobile menu clickable and redirect to homepage

Add Elections header, rename Members to Officers

---

backend/src/routes/EventsRoutes.ts
frontend/package-lock.json
frontend/src/components/ui/Header.tsx
frontend/src/components/ui/PageDashboard.tsx

Add functionality to add pages and links under the Elections header. Requested by Liam.
Other commits are useless, disregard

Elections dashboard

---

frontend/src/components/ui/Header.tsx

When a link from a navbar dropdown is clicked, the dropdown should close.

Fix header dropdown click

---

backend/src/services/EngageEventsService.ts
frontend/src/app/events/page.tsx
frontend/src/components/ui/HomepageEvents.tsx

1. Display only events that last less than 3 days in the calendar.
2. Correct the time mismatch between production events time and the actual time (Production was 7 - 8 hours ahead).
Note: I believe the time issue has been fixed, but I couldn't test it as the changes need to be merged into the main branch before testing the backend.

Fix events

---

backend/src/routes/AuthRoutes.ts
frontend/src/app/layout.tsx
frontend/src/app/page.tsx
frontend/src/components/ui/Header.tsx
frontend/src/components/ui/LoginAlert.tsx
frontend/src/middleware.ts

- updated logout route to properly destroy cookie and session
- created middleware.ts to remove access
- added "You need to be logged in to access any pages on ASPC." popup if not logged in creating/accessingNextjs search params loginRequired=True

require auth for all pages

---

backend/src/services/EngageEventsService.ts

Fix events time (subtract 7 hours instead of 8)

Fix events time

---

frontend/src/app/campus/courses/[id]/page.tsx

Add instructor for every review

---

backend/src/models/People.ts
backend/src/routes/InstructorsRoutes.ts
frontend/src/app/campus/courses/[id]/page.tsx
frontend/src/app/campus/instructors/[id]/page.tsx
frontend/src/app/campus/instructors/page.tsx
frontend/src/components/courses/CourseReview.tsx
frontend/src/components/courses/Review.tsx
frontend/src/types.ts

#81 
- **Instructor Collection:**
- Instructors collection now has:
- School affiliation (full name of a school)
- Past courses taught, including course IDs, course codes, and course names
- **New API Route (********`instructors/:id/courses`********):**
- New backend route to get courses associated with a specific instructor by their ID
- <img width="674" alt="instructorCourses" src="https://github.com/user-attachments/assets/1df39282-803e-49a8-8a62-2df02fedcdf0" />
- **CourseReview Component:**
- `CourseReview` component now accepts either an instructor or a course context
- This component is now used in instructor reviews page
- <img width="1463" alt="SCR-20250420-olgb" src="https://github.com/user-attachments/assets/8f79303e-2d74-4051-a9c3-f5a3c51de3f6" />
- **Instructor Reivews Page …

Instructors table restructure + Instructors page features (color and information)

---

docs/FEATURES.md
frontend/src/components/ui/Header.tsx
frontend/src/components/ui/PageDashboard.tsx

header changes requested by Liam
- about, officers, press room, resources, scs internship, events
- improved featues.md document

header change +docs

---

backend/src/routes/CoursesRoutes.ts
frontend/src/app/campus/courses/page.tsx

We have a parameter "number" in our course search query, but number is never set! Remove it from both the frontend and backend.

ASPC-16: Remove unecssary number parameter from course search

---

backend/src/models/People.ts
backend/src/routes/admin/StaffRoutes.ts
frontend/src/app/staff/[slug]/page.tsx
frontend/src/components/ui/StaffDashboard.tsx
frontend/src/types.ts

Previously, staff member emails were stored in the position field alongside the actual position title (e.g., "President [president@aspc.pomona.edu](mailto:president@aspc.pomona.edu)"). This approach was temporary and made data management and display inconsistent. This PR separates email into its own dedicated field.
Full-stack Implementation
- Database Schema: Added required email field to the Staff model with validation (trimmed, lowercase)
- Backend API: Updated staff routes to handle email field in create and update operations
- Admin Dashboard: Added dedicated email input field to the staff management form with proper state management
- Frontend Display: Email now displays as a clickable mailto: link on staff member cards, separate from the position
Migration Script
Created TypeScript …

ASPC-34: Adding Email Field to Staff Dashboard
